export const GAME_CONSTANTS = {
  TICK_RATE: 30,
  MAX_PLAYERS: 4,
  TERRAIN_CHUNK_SIZE: 32,
  PLAYER_MAX_SPEED: 10,
  WORM_ATTRACTION_RANGE: 300,
  THUMPER_DURATION: 60000,
  INTEREST_RANGE: 300,
  SNAPSHOT_INTERVAL: 5000,
};
