export const GAME_CONSTANTS = {
  TICK_RATE: 30,
  MAX_PLAYERS: 4,
  TERRAIN_CHUNK_SIZE: 32,
  PLAYER_MAX_SPEED: 10,
  WORM_ATTRACTION_RANGE: 300,
  THUMPER_DURATION: 60000,
  INTEREST_RANGE: 300,
  SNAPSHOT_INTERVAL: 5000,
  WORM_MOUNT_DISTANCE: 5,
  WORM_APPROACH_SLOW_DISTANCE: 15,
  WORM_MIN_SPEED: 5,
  WORM_MAX_SPEED: 25,
  WORM_TURN_RATE: Math.PI / 4,
  WORM_INITIAL_HEALTH: 1000,
};

export { COMBAT_CONSTANTS } from './combat.js';
export { VS4_CONSTANTS } from './vs4.js';
