export const VS4_CONSTANTS = {
  OUTPOST_CAPTURE_RADIUS: 35,
  OUTPOST_CAPTURE_TIME: 12,
  OUTPOST_DECAY_RATE: 0.5,
  OUTPOST_MIN_GARRISON: 3,
  OUTPOST_MAX_GARRISON: 5,
  BOT_BACKFILL_DELAY: 4,
  THUMPER_JAM_RADIUS: 45,
  THUMPER_JAM_DURATION: 20000,
  OUTPOST_REWARD_SPICE: 60,
  OUTPOST_REWARD_WATER: 30,
};
